# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: sutoj/builder:xenial
clone:
  depth: 20

pipelines:
  default:
    - step:
        script:
          - echo "Everything is awesome!"

  branches:
    bbpl:
      - step:
          script:
            - service mysql start
            - ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-database=mariadb --enable-tcpwrappers
            - make clean all install
            - echo "create database piler character set 'utf8mb4'" | mysql -u root
            - echo "grant all privileges on piler.* to piler@localhost identified by 'piler123'" | mysql -u root
            - echo "flush privileges" | mysql -u root
            - mysql -u piler -ppiler123 piler < /usr/share/piler/db-mysql.sql
            - cd unit_tests
            - ./run.sh
