# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: sutoj/builder:xenial
clone:
  depth: 20

pipelines:
  default:
    - step:
        script:
          - echo "Everything is awesome!"

  branches:
    bbpl:
      - step:
          script:
            - ./configure --prefix=/usr --sysconfdir=/etc --localstatedir=/var --with-database=mariadb --enable-tcpwrappers
            - make clean all
